[feature] receive POST and insert the data to firestore
kutsuzawa/slim-load-recorder pull request #3
Opened 2018-09-23 20:02 UTC by bookun

## 概要
postを受けて、dbにデータを登録

## 検証
README参照。
curl後にDBにpostしたデータが入っていればOK

2018-09-23 21:29 UTC, cappyzawa requested changes
Request changesってほどでもないが、Approveではないから🙅

2018-09-23 21:29 UTC, cappyzawa commented on README.md
> +$ make build
いらないっす

2018-09-23 21:29 UTC, cappyzawa commented on README.md
> +$ make build
ここもいらない

2018-09-23 21:29 UTC, cappyzawa commented on serverless.yml
> +          path: /line-post
今更だけどline-postっていうendpoint微妙だなー

POST `/line-post` ってちょっとな

2018-09-24 08:11 UTC, bookun commented
curlの返り値が `[{"date":"2018-09-24T07:26:12.385289Z","weight":71.8,"distance":5.2},{"date":"2018-09-24T07:26:19.983199Z","weight":71.8,"distance":5.2},{"date":"2018-09-24T07:27:28.805372Z","weight":71.8,"distance":5.2},{"date":"2018-09-24T07:56:39.05727Z","weight":71.8,"distance":5.2},{"date":"2018-09-24T08:00:35.328027Z","weight":71.8,"distance":5.2}]`
な感じなら意図したとおり

2018-09-24 12:16 UTC, cappyzawa approved these changes
若干修正漏れがあるものの、動作確認できたのでApprove

(loadsにするって話じゃなかったけ？

2018-09-24 12:16 UTC, cappyzawa commented on Makefile
> +	env GOOS=linux go build -o bin/add add/main.go
`load/main.go`

2018-09-24 12:16 UTC, cappyzawa commented on README.md
> +`$ curl -X POST http://localhost:3000/add -H 'Content-Type:application/json' -d '{"weight":71.8, "distance":5.2}' `
load

2018-09-24 13:24 UTC, cappyzawa approved these changes

2018-09-24 13:24 UTC, merged